### ISSUE TITLE
Notify data.gov team when deploy fails

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2827]
## User Story

As a data.gov developer, I want to be notified via a github issue when a deployment for an application fails so that the whole team is notified and we can triage quickly.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN an application is setup to deploy via GitHub Actions \
  WHEN the deploy fails \
  THEN a GitHub issue is created in datagov-deploy \
  AND links are added to be able to quickly triage

## Background
A v0.1 was developed for inventory, but [it was deemed too much code to copy/paste into various repo's](https://github.com/GSA/inventory-app/pull/241). This needs to be it's own repo as a published GitHub Action.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Everything is public, no security considerations here.

## Sketch
The code is already written, just need to setup the library correctly and take variable inputs (what repo do you want to create an issue on? etc). This will allow for customization later if we ever get rid of datagov-deploy... Should follow [GitHub Actions Documentation](https://docs.github.com/en/actions/creating-actions/about-actions)

Nick also turned up [this email example](https://www.ravsam.in/blog/send-email-notification-when-github-action-fails/)

**Comment by nickumia-reisys** [comment]
I brought this back from `archived` because recently, we've been having a lot of deployment failures and it would help I think..
- https://github.com/GSA/data.gov/issues/3973
- This run had to re-run 5 times and it magically worked afterwards
  - https://github.com/GSA/catalog.data.gov/actions/runs/3206176580
- This run had to be run 2 times
  - https://github.com/GSA/catalog.data.gov/actions/runs/3207685622

**Comment by nickumia-reisys** [comment]
To auto add issues to the board, the following action has been tested.
- https://github.com/actions/add-to-project

The following workflow must be added to each repo that we would like to auto-add issues from,
```yaml
name: add-to-project

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: '<project-url>'
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
```

Tested with both personal GH Project and GSA Org Project
- https://github.com/users/nickumia-reisys/projects/1
- https://github.com/orgs/GSA/projects/24/views/1

A GH Token must be created and added to the repos that run this action as well.  I used a personal token, but I know there is a way to create an organization token so that it's not tied to a particular user.  The token must have the following permissions:
- `project` -- Full control of projects

The following three triggers have been tested and work (but we don't need to implement all of them):
- New issue created
- New label added to issue
- New comment on issue
