### ISSUE TITLE
Script- and task-friendly Cloud Foundry GitHub Action

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3584]
## User Story

In order to minimize repeated code in workflows across repositories, the data.gov team wants a GitHub Action which makes it easy to employ the cf CLI in scripts.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] The GitHub Action we use should be one that someone else owns/maintains
- [x] GIVEN a script `create-services.sh` that uses the `cf`  CLI wth `--wait` parameters, \
  AND a GitHub Workflow job with a step like:
```
    - name: Create services
        uses: [someorg]/[some-image]@8
        with:
          command: ./create-services.sh
          org: gsa-datagov
          space: prod
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
```
  WHEN I invoke the workflow \
  THEN the workflow step successfully executes the script.
- [x] GIVEN a GitHub Workflow job with a step like:
```
    - name: Run a task
        uses: [someorg]/[some-image]@8
        with:
          cf_command: run-task APPNAME --name "my task" --command "some commands"
          org: gsa-datagov
          space: prod
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
```
  WHEN I invoke the workflow \
  THEN the workflow step successfully runs the task

Note the differences between `command:` and `cf_command:` above.

## Background

The USDS action we've been using [doesn't support `cf run-task` because of bad quoting practices](https://github.com/GSA/project-open-data-dashboard/pull/377) and every other GH Action we've looked at assumes that you will only be using it to call a CF subcommand, when we really need a way to [ensure the CLI is installed and authenticated](https://github.com/GSA/catalog.data.gov/commit/e49db68661e23f33e98bd699ece8b1ec4844c00e#diff-a84942e5e1a6a03941473db4dd19565981ab29f91888ba72ad91e97424465052) before we run [a script that uses it](https://github.com/GSA/catalog.data.gov/commit/e49db68661e23f33e98bd699ece8b1ec4844c00e#diff-be342bcf64fe0f504795990fca2870e6ac44b019e75ebc3a819fd2bd9d54e44d).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
So long as we use/contribute to a GH Action owned by a trusted partner such as cloud.gov, we will be reducing our dependence on a GH Action we don't control (the USDS one) and we will likely have an easier time making PRs in case of security issues.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- Make PRs to [the existing cloud.gov-owned GH Action](https://github.com/cloud-gov/cg-cli-tools), and avoid breaking its behavior for existing users.
